tap "homebrew/bundle"
tap "homebrew/cask"

# Shell & Terminal
brew "fish"
brew "chezmoi"
cask "ghostty"

# Development Tools
brew "git"
brew "vim"
brew "go"
brew "goenv"
brew "pyenv"
brew "python"
brew "ruby"
brew "nodebrew"

# CLI Tools
brew "awscli"
brew "gibo"
brew "wget"
brew "mas"

# Docker
brew "docker"
brew "docker-compose"
cask "docker"

# Applications
cask "1password"
cask "appcleaner"
cask "discord"
cask "fork"
cask "goland"
cask "google-chrome"
cask "google-cloud-sdk"
cask "slack"
cask "the-unarchiver"
cask "visual-studio-code"

# Mac App Store
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
